<a href="https://colab.research.google.com/github/shreya0181/Python/blob/master/AdvancedPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
a= np.array([5, 6, 9])
a[0]
# 2D array.
b= np.array([[4,5 ,6],[1,2,3], [7,8 ,9]])
b[0][0]
# Print Dimention of the array.
print("Dimention of the array.")
print(b.ndim)
# Print byte size the array.
print('\n')
print("Byte size of the array.")
print(b.itemsize)
# Set dtype.
print('\n')
print("Set dtype") 
a= np.array([[4,5],[1,2], [7,8]], dtype= np.float64)
print(a.itemsize)
print(a)
# Print shape/dimention of the array.
print('\n')
print("Print shape/width and height of the array.")
print(a.shape)
# Setting dytpe to complex.
print('\n')
print("Setting dytpe to complex.")
print(a)
# Zero array with given shape.
print('\n')
print("Zero array with given shape.")
a = np.zeros((3,4))
print(a)
# One's array with given shape.
print('\n')
print("One's array with given shape.")
a = np.ones((3,4))
print(a)
# Print an array using given range.
print('\n')
print("Print an array using given range.")
a = np.arange((6))
print(a)
# Print an array having steps of n numbers in a given range.
print('\n')
print("Print an array having steps of n numbers in a given range.")
a = np.arange(1,5, 2)
print(a)
# Print n numbers between two numbers using linspace.
# Linspace includes the range in the numbers.
# Returns an array of numbers in a linear sequence.
print('\n')
print("Print n numbers between two numbers using linspace.")
a = np.linspace(1,5, 10)
print(a)
# Print a reshaped/altered number of rows and columns array using reshape function.
print('\n')
print("Print a reshaped/altered number of rows and columns array using reshape function.")
a = np.reshape(5,1)
print(a)
#  Print a flattened array using ravel function.
print('\n')
print("Print a flattened array using ravel function.")
a = np.array([[1,2], [3,4], [5,6]])
print(a)
a = np.ravel(a)
print('\n')
print(a)
# Mathematical operation on an array.
print('\n')
print("Mathematical operation on an array.")
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print("Sum of the array:", a.sum())
print("Max of the array:", a.max())
print("Min of the array:", a.min())
print("Sum of vertical columns/ y-axis:", a.sum(axis=0))
print("Sum of vertical rows/ x-axis:", a.sum(axis=1))
# Non-generic functions.
print("Std deviation of an array:", np.std(a))
print("Square root of an array:", np.sqrt(a))

# Operation on n arrays.
print('\n')
a = np.array([[1,2], [3,4], [5,6]])
b= np.array([[5,6,],[7,8], [9, 10]])
print(a)
print(b)
print("Sum of two arrays:\n", a+b)
print("Product of two arrays:\n", a*b)
print("Difference of two arrays:\n", a-b)







Dimention of the array.
2


Byte size of the array.
8


Set dtype
8
[[4. 5.]
 [1. 2.]
 [7. 8.]]


Print shape/width and height of the array.
(3, 2)


Setting dytpe to complex.
[[4. 5.]
 [1. 2.]
 [7. 8.]]


Zero array with given shape.
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


One's array with given shape.
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Print an array using given range.
[0 1 2 3 4 5]


Print an array having steps of n numbers in a given range.
[1 3]


Print n numbers between two numbers using linspace.
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Print a reshaped/altered number of rows and columns array using reshape function.
[5]


Print a flattened array using ravel function.
[[1 2]
 [3 4]
 [5 6]]


[1 2 3 4 5 6]


Mathematical operation on an array.
[[1 2]
 [3 4]
 [5 6]]
Sum of the array: 21
Max of the array: 6
Min of the array: 1
Sum of vertical columns/ y-axis: [ 9 12]
Sum of vertical rows/

Pandas


In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/pandas/1_intro/nyc_weather.csv")
print("Print first five enteries of the csv file.")
print(df.head())
# Max value in a column.
print("\n")
print("Max value in a column.")
print(df['Temperature'].max()) 
# 
print("\n")
rain_events = df['EST'][df['Events']=="Rain"]
print(rain_events)
# Mean of enteries.
print("\n")
print("Print mean of entries.")
print(df['WindSpeedMPH'].mean())
# Data Cleaning: Data Munging/ Data Munging:- using fillna, dropna
print("\n")
print("Data Cleaning: called as Data Munging or Data Cleaning.")
df.fillna(0, inplace=True)
print(df)


# Dataframe basics.
# Dataframes is main object in Pandas. It is used to represent data with rows and columns( tabular or excel spreadsheet like data).
# 1.Creating DataFrame.
# 2.Dealing with rows and columns.
# 3.Operations: min, max, std, describe.
# 4.Conditional selection.
# 5.set_index.

# Creating a DataFrame.
print("\n")

weather_data = {
    'day': ['1/1/2017','1/2/2017', '1/3/2017', '1/4/2017', '1/6/2017', '2/7/2017','8/7/2017'],
    'temprature': [32, 35, 28, 24, 32, 31,7 ],
    'windspeed': [6, 7, 2, 7, 4, 2,8],
    'event':['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny', 'Sunny']
}
df = pd.DataFrame(weather_data)
print(df)

# Dealing with rows and columns.
print("\n")
rows, columns = df.shape
print('Rows:{} and Clomuns: {}', [rows, columns])
# Print columns.
print("\n")
print("Print columns.", df.columns)
# Print type of column. In dataframe the column type is series.
print("\n")
print("In dataframe the column type is series.")
print(type(df['event']))
# Fetching multiple columns in a dataframe.
print("\n")
print("Fetching multiple columns in a dataframe.")
print(df[['event', 'temprature', 'day']])
# Print max of a column.
print("\n")
print("Print max of a column.")
print(df['temprature'].max())
# Print all operations using describe.
print("\n")
print("Print all operations using describe.")
print(df.describe())
# Perform inequality in dataframe.
print("\n")
print("Perform inequality in dataframe.")
print(df[df.temprature>=32])
# Slicing of DataFrame.
print("\n")
print("Slicing of DataFrame.")
print(df[2:5])
# Set a column name as index.
print("\n")
print("Set a column name as index.")
# Setting inplace true will update the dataframe.
df.set_index('day', inplace=True)
print(df)
# Setting day as index we can use any date as index using loc.
print("\n")
print("Setting day as index we can use any date as index using loc.")
print(df.loc['1/1/2017'])
# Reset index to original index.
print("\n")
print("Reset index to original index.")
df.reset_index(inplace= True)
print(df)







Print first five enteries of the csv file.
        EST  Temperature  DewPoint  ...  CloudCover  Events  WindDirDegrees
0  1/1/2016           38        23  ...           5     NaN             281
1  1/2/2016           36        18  ...           3     NaN             275
2  1/3/2016           40        21  ...           1     NaN             277
3  1/4/2016           25         9  ...           3     NaN             345
4  1/5/2016           20        -3  ...           0     NaN             333

[5 rows x 11 columns]


Max value in a column.
50


8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object


Print mean of entries.
6.892857142857143


Data Cleaning: called as Data Munging or Data Cleaning.
          EST  Temperature  DewPoint  ...  CloudCover    Events  WindDirDegrees
0    1/1/2016           38        23  ...           5         0             281
1    1/2/2016           36        18  ...           3         0             275
2    1/3/2016     

Differentt ways of creationg dictionary

In [ ]:
# 1.Using CSV.
# 2.Using Excel.
# 3.From Python Dictionary.
# 4.From list of tuples.
# 5.From list of dictionaries.

# Read CSV.
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/pandas/1_intro/nyc_weather.csv")
print(df.head())
# Using pandas dataFrame.
weather_data = {
    'day': ['1/1/2017','1/2/2017', '1/3/2017', '1/4/2017', '1/6/2017', '2/7/2017','8/7/2017'],
    'temprature': [32, 35, 28, 24, 32, 31,7 ],
    'windspeed': [6, 7, 2, 7, 4, 2,8],
    'event':['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny', 'Sunny']
}
df = pd.DataFrame(weather_data)
print("\n")
print(df)

# Creating a dataframe using a tuples list.
print("\n")
weather_data = [
    ('1/1/2019', 32, 6, 'Rain'),
    ('1/2/2017', 35, 7, 'Sunny'),
    ('28/2/2017', 28, 2, 'Snow')
]
df = pd.DataFrame(weather_data, columns= ['day', 'temprature', 'windspeed', 'weather'])
print(df)


        EST  Temperature  DewPoint  ...  CloudCover  Events  WindDirDegrees
0  1/1/2016           38        23  ...           5     NaN             281
1  1/2/2016           36        18  ...           3     NaN             275
2  1/3/2016           40        21  ...           1     NaN             277
3  1/4/2016           25         9  ...           3     NaN             345
4  1/5/2016           20        -3  ...           0     NaN             333

[5 rows x 11 columns]


        day  temprature  windspeed  event
0  1/1/2017          32          6   Rain
1  1/2/2017          35          7  Sunny
2  1/3/2017          28          2   Snow
3  1/4/2017          24          7   Snow
4  1/6/2017          32          4   Rain
5  2/7/2017          31          2  Sunny
6  8/7/2017           7          8  Sunny


         day  temprature  windspeed weather
0   1/1/2019          32          6    Rain
1   1/2/2017          35          7   Sunny
2  28/2/2017          28          2    Snow
